/* eslint-disable camelcase */
import { ReactNode } from 'react'
import './globals.css'
import { Source_Serif_4 } from 'next/font/google'

const source_serif = Source_Serif_4({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`grid h-screen place-content-center ${source_serif.className}`}
      >
        {children}
      </body>
    </html>
  )
}
